---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-example-octodex
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 4
  selector:
    matchLabels:
      app: aws-example-octodex
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: aws-example-octodex
    spec:
      containers:
      - name: aws-example-octodex
        # image: 00000000000000.dkr.ecr.my-region.amazonaws.com/example-eks:tag
        image: 991225764181.dkr.ecr.us-west-2.amazonaws.com/example-eks:bfc7023f90852dfd15fb0a9800182b3ca432b0f9
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
